Enable debug mode

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -19,6 +19,11 @@ inputs:
     required: false
     default: '3.10'
     choices: ['3.12', '3.11', '3.10', '3.9', '3.8', '3.7']
+  debug:
+    description: 'Whether to run in debug mode'
+    required: false
+    default: 'false'
+    choices: ['true', 'false']
   ruff-version:
     description: 'The version of ruff to use'
     required: false
@@ -69,6 +74,7 @@ runs:
         install_flake8_formatter_linters=('ruff', 'flake8')
         EXTRA_PIP_FLAGS=''
         LINTER_VERSION_CONSTRAINT=''
+        EXTRA_LINTER_SCRIPT_FLAGS=''
         if [[ "${linters[*]}" =~ (^|[^[:alpha:]])${INPUTS_LINTER}([^[:alpha:]]|$) ]]; then
           if [[ "${INPUTS_LINTER}" == "fixit" ]]; then
             if [[ "${INPUTS_FIXIT_VERSION}" == "latest" ]]; then
@@ -110,7 +116,11 @@ runs:
             "${PYTHON_CMD}" -mpip install flake8-sarif-formatter || ( echo "::error::flake8-sarif-formatter failed to install for Python ${INPUTS_PYTHON_VERSION}" && exit 1 )
           fi
 
-          "${PYTHON_CMD}" "${GITHUB_ACTION_PATH}"/python_lint.py "${INPUTS_LINTER}" --target="${INPUTS_TARGET}" --output="${GITHUB_WORKSPACE}/${INPUTS_OUTPUT}" || ( echo "::error::${INPUTS_LINTER} failed to run for Python ${INPUTS_PYTHON_VERSION}" && exit 1 )
+          if [[ "${INPUTS_DEBUG}" == "true" ]]; then
+            EXTRA_LINTER_SCRIPT_FLAGS=" --debug"
+          fi
+
+          "${PYTHON_CMD}" "${GITHUB_ACTION_PATH}"/python_lint.py "${INPUTS_LINTER}" --target="${INPUTS_TARGET}" --output="${GITHUB_WORKSPACE}/${INPUTS_OUTPUT}" ${EXTRA_LINTER_SCRIPT_FLAGS} || ( echo "::error::${INPUTS_LINTER} failed to run for Python ${INPUTS_PYTHON_VERSION}" && exit 1 )
         else
           echo "::error::invalid linter ${INPUTS_LINTER}; choose one of ${linters[*]}"
           exit 1
@@ -127,6 +137,7 @@ runs:
         INPUTS_PYRIGHT_VERSION: ${{ inputs.pyright-version }}
         INPUTS_PYTYPE_VERSION: ${{ inputs.pytype-version }}
         INPUTS_FIXIT_VERSION: ${{ inputs.fixit-version }}
+        INPUTS_DEBUG: ${{ inputs.debug }}
       shell: bash
     - name: Upload SARIF
       if: ${{ hashFiles(inputs.output) != '' }}
